SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `te`;
CREATE TABLE `te` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'te',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1032 DEFAULT CHARSET=utf8;